# -*- coding: utf-8 -*-
"""LGBTIQ.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NrvpOfrL0OzhY6ZYP7MGyXUv30gpn999
"""

import streamlit as st

# Título de la aplicación
st.title("Expresiones de Género LGBTIQ")
st.image("gifqr.gif", caption="UST-URC Universidad Rosario Castellanos", width=300)


# Introducción
st.write("""
Esta aplicación tiene como objetivo educar sobre las diferentes expresiones de género y orientaciones dentro de la comunidad LGBTIQ.
Utiliza el menú desplegable a continuación para explorar términos específicos.
""")

# Diccionario de términos con multimedia
terminos = {
    "Lesbiana": {
        "descripcion": "Mujer que se siente atraída romántica y/o sexualmente hacia otras mujeres.",
        "imagen": "URC.png"
    },
    "Gay": {
        "descripcion": "Hombre que se siente atraído romántica y/o sexualmente hacia otros hombres.",
        "imagen": "URC.png"
    },
    "Bisexual": {
        "descripcion": "Persona que se siente atraída romántica y/o sexualmente hacia personas de más de un género.",
        "imagen": "URC.png"
    },
    "Transgénero": {
        "descripcion": "Persona cuya identidad de género es diferente del sexo que se le asignó al nacer.",
        "imagen": "URC.png"
    },
    "Intersex": {
        "descripcion": "Persona que nace con características sexuales que no encajan en las definiciones típicas de masculino o femenino.",
        "imagen": "URC.png"
    },
    "Queer": {
        "descripcion": "Término general que abarca diversas identidades que no se ajustan a las normas de género y sexualidad tradicionales.",
        "imagen": "URC.png"
    },
    "Asexual": {
        "descripcion": "Persona que no siente atracción sexual o la siente en un grado muy bajo.",
        "imagen": "URC.png"
    },
    "Pansexual": {
        "descripcion": "Persona que se siente atraída por otros sin importar su género.",
        "imagen": "URC.png"
    },
}

# Menú desplegable para seleccionar un término
term_selected = st.selectbox("Selecciona un término:", list(terminos.keys()))

# Mostrar descripción y multimedia del término seleccionado
if term_selected in terminos:
    st.subheader(term_selected)
    st.write(terminos[term_selected]["descripcion"])
    st.image(terminos[term_selected]["imagen"], caption=f"Bandera de {term_selected}")

# Sección de recursos adicionales
st.header("Recursos Adicionales")
st.write("""
- [Wikipedia: LGBTIQ](https://es.wikipedia.org/wiki/LGBT)
- [Asociaciones y grupos de apoyo LGBTIQ](https://www.lambdalegal.org/)
- [Guías sobre diversidad de género](https://www.glaad.org/)
""")

# Footer
st.write("Desarrollado por [Perspectiva de Género para el Diseño Social].")

# Personalización de diseño
st.markdown("""
<style>
    .stApp {
        background-color: #0000ff;
    }
    .css-1d391kg {
        color: #4a4a4a;
    }
</style>
""", unsafe_allow_html=True)