# -*- coding: utf-8 -*-
"""LGBTIQ.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NrvpOfrL0OzhY6ZYP7MGyXUv30gpn999
"""

import streamlit as st

# Título de la aplicación
st.title("Expresiones de Género LGBTIQ+")
st.image("URC.png", caption="UST-URC Universidad Rosario Castellanos", width=200)



# Introducción
st.write("""
Esta aplicación tiene como objetivo educar sobre las diferentes expresiones de género y orientaciones dentro de la comunidad LGBTIQ.
Utiliza el menú desplegable a continuación para explorar términos específicos.
""")

# Diccionario de términos con multimedia
terminos = {
    "Lesbiana": {
        "descripcion": "Mujer que se siente atraída romántica y/o sexualmente hacia otras mujeres.",
        "gif": "gifqr.gif"
    },
    "Gay": {
        "descripcion": "Hombre que se siente atraído romántica y/o sexualmente hacia otros hombres.",
        "gif": "gifqr.gif"
    },
    "Bisexual": {
        "descripcion": "Persona que se siente atraída romántica y/o sexualmente hacia personas de más de un género.",
        "gif": "gifqr.gif"
    },
    "Transgénero": {
        "descripcion": "Persona cuya identidad de género es diferente del sexo que se le asignó al nacer.",
        "gif": "gifqr.gif"
    },
    "Intersex": {
        "descripcion": "Persona que nace con características sexuales que no encajan en las definiciones típicas de masculino o femenino.",
        "gif": "gifqr.gif"
    },
    "Queer": {
        "descripcion": "Término general que abarca diversas identidades que no se ajustan a las normas de género y sexualidad tradicionales.",
        "gif": "gifqr.gif"
    },
    "Asexual": {
        "descripcion": "Persona que no siente atracción sexual o la siente en un grado muy bajo.",
        "gif": "gifqr.gif"
    },
    "Pansexual": {
        "descripcion": "Persona que se siente atraída por otros sin importar su género.",
        "gif": "gifqr.gif"
    },
}

# Menú desplegable para seleccionar un término
term_selected = st.selectbox("Selecciona un término:", list(terminos.keys()))

# Mostrar descripción y GIF del término seleccionado con tamaño ajustado
if term_selected in terminos:
    st.subheader(term_selected)
    st.write(terminos[term_selected]["descripcion"])
    st.image(terminos[term_selected]["gif"], caption=f"GIF representativo de {term_selected}")

# Personalización de diseño
st.markdown("""
<style>
    .stApp {
        background-color:  #da3262;
    }
    .css-1d391kg {
        color:  #faf7f8;
    }
</style>
""", unsafe_allow_html=True)

# Añadir la línea separadora
st.markdown("<hr>", unsafe_allow_html=True)

# Sección de recursos adicionales
st.header("Recursos Adicionales")
st.write("Encuesta Nacional sobre la Diversidad Sexual y de Género (ENDISEG) 2021. (ENEGI)")
st.write("https://www.inegi.org.mx/programas/endiseg/2021/#microdatos")

# Añadir la línea separadora
st.markdown("<hr>", unsafe_allow_html=True)

# Insertar el código HTML con estilos personalizados
st.markdown("""
    <div class="container col-sm-5 creditos text-center">
        <p style="margin-top:0;margin-bottom:0;font-size:15px;color: #424040;text-align:center">
            <strong>Colaboración:</strong>
        </p>
        <p style="margin-top:0;margin-bottom:0;font-size:12px;color:  #979394 ;text-align:center">
            <strong>Asignatura (UCA): Perspectiva de Género para el Diseño Social  LCFI-URC</strong>
        </p>
        <p style="margin-top:0;margin-bottom:0;font-size:12px;color:  #979394 ;text-align:center">
            <strong>Grupos 104 y 107 COY-LCFI-URC</strong>
        </p>
    </div>
""", unsafe_allow_html=True)